[project]
name = "data-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas==2.3.3",
    "prefect[sqlalchemy]>=3.6.15",
    "psycopg2==2.9.11",
    "pyarrow>=23.0.0",
    "sqlalchemy==2.0.46",
]
